# Copied from reth v1.8.1
# Ignored Tests Configuration
#
# This file contains tests that should be ignored for various reasons (flaky, known issues, etc).
# These tests will be IGNORED in the CI results - they won't cause the build to fail
# regardless of whether they pass or fail.
#
# Format
# test_suite:
#   - "test name 1"
#   - "test name 2"
#
# When a test should no longer be ignored, remove it from this list.

# flaky
engine-withdrawals:
  - Withdrawals Fork on Block 1 - 8 Block Re-Org NewPayload (Paris) (bera-reth)
  - Withdrawals Fork on Block 8 - 10 Block Re-Org NewPayload (Paris) (bera-reth)
  - Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org (Paris) (bera-reth)
  - Sync after 128 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts (Paris) (bera-reth)
engine-cancun:
  - Transaction Re-Org, New Payload on Revert Back (Cancun) (bera-reth)
  - Transaction Re-Org, Re-Org to Different Block (Cancun) (bera-reth)
  - Transaction Re-Org, Re-Org Out (Cancun) (bera-reth)
  - Multiple New Payloads Extending Canonical Chain, Wait for Canonical Payload (Cancun) (bera-reth)
engine-api:
  - Transaction Re-Org, Re-Org Out (Paris) (bera-reth)
  - Transaction Re-Org, Re-Org to Different Block (Paris) (bera-reth)
  - Transaction Re-Org, New Payload on Revert Back (Paris) (bera-reth)
  - Transaction Re-Org, Re-Org to Different Block (Paris) (bera-reth)
  - Invalid Missing Ancestor Syncing ReOrg, Transaction Nonce, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Paris) (bera-reth)
  - Invalid Missing Ancestor Syncing ReOrg, Transaction Signature, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Paris) (bera-reth)
  - Invalid Missing Ancestor Syncing ReOrg, Transaction Signature, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Paris) (bera-reth)
  - Multiple New Payloads Extending Canonical Chain, Wait for Canonical Payload (Paris) (bera-reth)
  - Multiple New Payloads Extending Canonical Chain, Set Head to First Payload Received (Paris) (bera-reth)

