name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      make-target:
        description: 'Makefile target to run'
        required: true
        type: string
      profile:
        description: 'Cargo profile to use'
        required: false
        type: string
        default: 'release'
      dry-run:
        description: 'Dry run mode (build but do not push)'
        required: false
        type: boolean
        default: false

env:
  IMAGE_NAME: ${{ github.repository_owner }}/bera-reth
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bera-reth
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.arch }} Docker image
        run: |
          if [[ "${{ inputs.dry-run }}" == "true" ]]; then
            echo "Dry run mode - building without pushing"
            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} PROFILE=${{ inputs.profile }} make docker-build-local-${{ matrix.arch }}
          else
            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} PROFILE=${{ inputs.profile }} make docker-build-push-${{ matrix.arch }}
          fi

  docker-manifest:
    needs: docker-build
    runs-on: ubuntu-latest
    if: inputs.dry-run != true
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          if [[ "${{ inputs.make-target }}" == *"latest"* ]]; then
            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} make docker-manifest-create-latest
          else
            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} make docker-manifest-create
          fi
